### ISSUE TITLE
Add ProtonVPN examples and PR check

### ISSUE THREAD

**Issue by miklosbagi** [miklosbagi/gluetrans#30]

**Comment by adriy-be** [comment]
ProtonVPN examples, so not sure about DOCKER_MODS and VPN_PORT_FORWARDING_PROVIDER
Hope than can help :)

```yaml
version: "3"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - USER=
      - PASS=
      - DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
    volumes:
      - :/config
      - :/downloads
      - :/watch
        #    ports:
        #- 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    network_mode: "service:vpn_gateway"
    restart: unless-stopped

  vpn_gateway:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Brussels
      - PUID=1000
      - PGID=1000

      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=

      - SERVER_COUNTRIES=
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    ports:
      - 9091:9091
      
  gluetrans:
    image: miklosbagi/gluetrans:latest
    environment:
      GLUETUN_CONTROL_ENDPOINT: http://localhost:8000
      GLUETUN_HEALTH_ENDPOINT: http://localhost:9999
      TRANSMISSION_ENDPOINT: http://localhost:9091/transmission/rpc
      TRANSMISSION_USER: adri
      TRANSMISSION_PASS: "@zertyuiop"
      PEERPORT_CHECK_INTERVAL: 30 # optional, default: 15, in seconds
      GLUETUN_PICK_NEW_SERVER_AFTER: 15 # optional, default: 10, in number of retries
      FORCED_COUNTRY_JUMP: 0 # optional, default: 0 (means: disabled). Example: 120 (jump to new country every 2 hours)
    network_mode: "service:vpn_gateway" # go through gluetun's VPN
    depends_on:
      - vpn_gateway
```

**Comment by adriy-be** [comment]
ProtonVPN examples, so not sure about DOCKER_MODS and VPN_PORT_FORWARDING_PROVIDER
Hope than can help :)

```yaml
version: "3"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - USER=
      - PASS=
      - DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
    volumes:
      - :/config
      - :/downloads
      - :/watch
        #    ports:
        #- 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    network_mode: "service:vpn_gateway"
    restart: unless-stopped

  vpn_gateway:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Brussels
      - PUID=1000
      - PGID=1000

      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=

      - SERVER_COUNTRIES=
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    ports:
      - 9091:9091
      
  gluetrans:
    image: miklosbagi/gluetrans:latest
    environment:
      GLUETUN_CONTROL_ENDPOINT: http://localhost:8000
      GLUETUN_HEALTH_ENDPOINT: http://localhost:9999
      TRANSMISSION_ENDPOINT: http://localhost:9091/transmission/rpc
      TRANSMISSION_USER:
      TRANSMISSION_PASS:
      PEERPORT_CHECK_INTERVAL: 30 # optional, default: 15, in seconds
      GLUETUN_PICK_NEW_SERVER_AFTER: 15 # optional, default: 10, in number of retries
      FORCED_COUNTRY_JUMP: 0 # optional, default: 0 (means: disabled). Example: 120 (jump to new country every 2 hours)
    network_mode: "service:vpn_gateway" # go through gluetun's VPN
    depends_on:
      - vpn_gateway
```

**Comment by adriy-be** [comment]
ProtonVPN examples, so not sure about DOCKER_MODS and VPN_PORT_FORWARDING_PROVIDER
Hope than can help :)

```yaml
version: "3"
services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=
      - USER=
      - PASS=
      - DOCKER_MODS="jordanpotter/docker-mods:transmission-nat-pmp"
    volumes:
      - :/config
      - :/downloads
      - :/watch
        #    ports:
        #- 9091:9091
        #- 51413:51413
        #- 51413:51413/udp
    network_mode: "service:vpn_gateway"
    restart: unless-stopped

  vpn_gateway:
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=
      - PUID=1000
      - PGID=1000

      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=

      - SERVER_COUNTRIES=
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
    ports:
      - 9091:9091
      
  gluetrans:
    image: miklosbagi/gluetrans:latest
    environment:
      GLUETUN_CONTROL_ENDPOINT: http://localhost:8000
      GLUETUN_HEALTH_ENDPOINT: http://localhost:9999
      TRANSMISSION_ENDPOINT: http://localhost:9091/transmission/rpc
      TRANSMISSION_USER:
      TRANSMISSION_PASS:
      PEERPORT_CHECK_INTERVAL: 30 # optional, default: 15, in seconds
      GLUETUN_PICK_NEW_SERVER_AFTER: 15 # optional, default: 10, in number of retries
      FORCED_COUNTRY_JUMP: 0 # optional, default: 0 (means: disabled). Example: 120 (jump to new country every 2 hours)
    network_mode: "service:vpn_gateway" # go through gluetun's VPN
    depends_on:
      - vpn_gateway
```
